import { useEffect, useMemo, useState } from 'react'
import { QRCodeSVG } from 'qrcode.react'
import { supabase } from '../lib/supabase'
import { money, notify } from '../lib/utils'
import { Card, Empty, ErrorText, SuccessText } from '../components/Ui'

type Member = { id: string; employee_id: string; full_name: string; balance: number }
type Item = { id: string; name: string; sku: string; selling_price: number }
type Cart = Item & { qty: number }
type Order = { id: string; invoice_no: string; total: number; status: string; created_at: string; members: { full_name: string } | null }
export function OrdersPage() {
  const [members, setMembers] = useState<Member[]>([]); const [items, setItems] = useState<Item[]>([]); const [orders, setOrders] = useState<Order[]>([]); const [memberId, setMemberId] = useState(''); const [search, setSearch] = useState(''); const [cart, setCart] = useState<Cart[]>([]); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null); const [receipt, setReceipt] = useState<Order | null>(null)
  const load = async () => { const [{ data: m }, { data: i }, { data: o }] = await Promise.all([supabase.from('member_balances').select('*').eq('status','active').order('full_name'), supabase.from('menu_items').select('id,name,sku,selling_price').eq('active',true).order('name'), supabase.from('orders').select('id,invoice_no,total,status,created_at,members(full_name)').order('created_at',{ascending:false}).limit(20)]); setMembers((m as Member[]) || []); setItems((i as Item[]) || []); setOrders((o as unknown as Order[]) || []) }
  useEffect(() => { load() }, [])
  const shown = items.filter(i => `${i.name} ${i.sku}`.toLowerCase().includes(search.toLowerCase())).slice(0, 12)
  const total = useMemo(() => cart.reduce((a, x) => a + x.selling_price * x.qty, 0), [cart])
  const add = (i: Item) => setCart(c => c.some(x => x.id === i.id) ? c.map(x => x.id === i.id ? { ...x, qty: x.qty + 1 } : x) : [...c, { ...i, qty: 1 }])
  const post = async () => { setError(null); setSuccess(null); if (!memberId || !cart.length) return setError('Select a member and add at least one item.'); const key = crypto.randomUUID(); const { data, error } = await supabase.rpc('create_order', { p_member_id: memberId, p_items: cart.map(x => ({ menu_item_id: x.id, quantity: x.qty })), p_idempotency_key: key }); if (error) return setError(error.message); setSuccess('Order posted successfully.'); setCart([]); const order = Array.isArray(data) ? data[0] : data; if (order) { const receiptOrder = { ...order, members: { full_name: members.find(m => m.id === memberId)?.full_name || '' } } as Order; setReceipt(receiptOrder); notify('SnackFlow order posted', `${receiptOrder.invoice_no} — ${money(receiptOrder.total)}`) } load() }
  const voidOrder = async (id: string) => { if (!confirm('Void this order and refund the wallet?')) return; const { error } = await supabase.rpc('void_order', { p_order_id: id, p_reason: 'Voided from application' }); if (error) setError(error.message); else load() }
  return <><div className="page-title"><div><h1>Daily Orders</h1><p>Atomic wallet deduction, receipt and refund-safe voiding</p></div></div><ErrorText error={error}/><SuccessText text={success}/>
    <div className="grid-2 orders-grid"><Card title="Build order"><label>Member<select value={memberId} onChange={e => setMemberId(e.target.value)}><option value="">Select member</option>{members.map(m => <option key={m.id} value={m.id}>{m.employee_id} — {m.full_name} ({money(m.balance)})</option>)}</select></label><label>Search by name / SKU<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Scan or type…"/></label><div className="item-grid">{shown.map(i => <button className="item-btn" key={i.id} onClick={() => add(i)}><b>{i.name}</b><small>{i.sku} · {money(i.selling_price)}</small></button>)}</div></Card>
      <Card title="Cart">{cart.length ? <>{cart.map(x => <div className="cart-row" key={x.id}><div><b>{x.name}</b><small>{x.qty} × {money(x.selling_price)}</small></div><div><button className="tiny" onClick={() => setCart(c => c.map(y => y.id === x.id ? { ...y, qty: Math.max(1, y.qty - 1) } : y))}>−</button><button className="tiny" onClick={() => setCart(c => c.map(y => y.id === x.id ? { ...y, qty: y.qty + 1 } : y))}>+</button><button className="tiny danger-btn" onClick={() => setCart(c => c.filter(y => y.id !== x.id))}>×</button></div></div>)}<div className="cart-total"><span>Total</span><strong>{money(total)}</strong></div><button onClick={post}>Post order</button></> : <Empty text="Add menu items to begin."/>}</Card></div>
    {receipt && <Card title="Latest receipt" actions={<button className="secondary" onClick={() => window.print()}>Print / PDF</button>}><div className="receipt"><QRCodeSVG value={`${location.origin}${import.meta.env.BASE_URL}?invoice=${receipt.invoice_no}`} size={96}/><div><h3>{receipt.invoice_no}</h3><p>{receipt.members?.full_name}</p><strong>{money(receipt.total)}</strong></div></div></Card>}
    <Card title="Recent orders">{orders.length ? <div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Member</th><th>Time</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>{orders.map(o => <tr key={o.id}><td>{o.invoice_no}</td><td>{o.members?.full_name}</td><td>{new Date(o.created_at).toLocaleString()}</td><td>{money(o.total)}</td><td>{o.status}</td><td>{o.status === 'posted' && <button className="tiny danger-btn" onClick={() => voidOrder(o.id)}>Void</button>}</td></tr>)}</tbody></table></div> : <Empty/>}</Card>
  </>
}
